title: IWW NYC GMB · Industrial Workers of the World
email: nyc-gmb@wobblycity.org
baseurl: ""
url: "https://wobblycity.org"

twitter_username: iwwnyc
github_username: iwwnyc
facebook_username: nyciww
instagram_username: iwwnyc
