title: IWW NYC GMB · Industrial Workers of the World
email: nyc-gmb@wobblycity.org
baseurl: ""
url: "https://wobblycity.org"
description: The latest news and happenings from the NYC Industrial Workers of the World! Join the General Membership Branch today and organize your workplace!

future: true

twitter_username: iwwnyc
github_username: iww-nyc-gmb
facebook_username: nyciww
instagram_username: iwwnyc

social:
  name: IWW NYC GMB
  links:
    - https://www.twitter.com/iwwnyc
    - https://www.facebook.com/nyciww
    - https://instagram.com/iwwnyc
    - https://github.com/iww-nyc-gmb

twitter:
  username: iwwnyc
  card: summary

facebook:
  publisher: nyciww

markdown: kramdown

kramdown:
  parse_span_html: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

image: /assets/social.png
logo: /assets/logo.png

collections:
  events:
    output: true
    path: ""
    permalink: /events/:path/

paginate: 5
paginate_path: "/news/:num/"
