title: IWW Vancouver GMB · Industrial Workers of the World
email: contact@vancouveriww.org
baseurl: ""
url: "https://vancouveriww.org"
description: The latest news and happenings from the Vancouver Industrial Workers of the World! · An injury to one is an injury to all.

future: true

twitter_username: vancouveriww
github_username: vancouveriww
facebook_username: vancouveriww
instagram_username: vancouveriww

social:
  name: IWW Vancouver GMB
  links:
    - https://www.twitter.com/vancouveriww
    - https://www.facebook.com/vancouveriww
    - https://instagram.com/vancouveriww
    - https://github.com/vancouveriww

twitter:
  username: vancouveriww
  card: summary

facebook:
  publisher: vancouveriww

markdown: kramdown

kramdown:
  parse_span_html: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

image: /assets/social.png
logo: /assets/logo.png

collections:
  events:
    output: true
    path: ""
    permalink: /events/:path/

paginate: 5
paginate_path: "/news/:num/"
