title: IWW NYC GMB · Industrial Workers of the World
email: nyc-gmb@wobblycity.org
baseurl: ""
url: "https://static.wobblycity.org"

future: true

twitter_username: iwwnyc
github_username: iww-nyc-gmb
facebook_username: nyciww
instagram_username: iwwnyc

markdown: kramdown
  hard_wrap: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

image: /assets/social.png

collections:
  events:
    output: true
    path: ""
    permalink: /events/:path/

paginate: 5
paginate_path: "/news/:num/"
