title: IWW NYC GMB · Industrial Workers of the World
email: nyc-gmb@wobblycity.org
baseurl: ""
url: "https://wobblycity.org"

future: true

twitter_username: iwwnyc
github_username: iww-nyc-gmb
facebook_username: nyciww
instagram_username: iwwnyc

next_meeting_url: /events/november-2018/
next_meeting_date: Tuesday, November 20, 2018
meeting_time: 7 to 9 PM

markdown: redcarpet

collections:
  events:
    output: true
    path: ""
    permalink: /events/:path/
    
    paginate: 10
paginate_path: "/news/page:num/"
