backend:
  name: github
  repo: IWW-NYC-GMB/IWW-NYC-GMB.github.io # Path to your GitHub repository

display_url: https://static.wobblycity.org

logo_url: /assets/iww_netlify.png

# publish_mode: editorial_workflow

media_folder: "assets/uploads"

collections:
  - name: "news"
    editor:
      preview: false
    label: "News" # Used in the UI
    folder: "news/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Categories", name: "categories", widget: "string", hint: "Enter 'newsletter' to send to Mailchimp", required: false}
      - {label: "Send to Mailchimp", name: "newsletter", widget: "boolean", hint: "Does not currently work", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/:categories/:year/:i_month/:i_day/:slug"}
  - name: "events"
    editor:
      preview: false
    label: "Events"
    label_singular: "Event"
    folder: "_events"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "dddd, MMMM Do, YYYY"}
      - {label: "Time", name: "time", widget: "string"}    
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'settings'
    label: 'Next Meeting Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Next Meeting Settings'
        file: '_config_test.yml'
        description: 'Next Meeting Settings'
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
          - {label: "test", name: "test", widget: "hidden", default: "123"}
          - {label: "Next Meeting URL", name: "next_meeting_url", widget: "string"}
          - {label: "Next Meeting Date", name: "next_meeting_date", widget: "string"}
          - {label: "Meeting Time", name: "meeting_time", widget: "string"}
